version: "3.0"

services:

  # --------------------------- HTTP and WS server --------------------------- #

  server:
    build:
      context: .
    container_name: server
    env_file:
      - .env
    expose:
      - "80"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - docker_net
    pid: host
    restart: unless-stopped
    volumes:
      - "./logs:/app/logs"

networks:
  docker_net: